### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by DarthMech** [bitrise-steplib/steps-activate-ssh-key#14]
Hi. Need help:

id: activate-ssh-key                                                         |
| version: 4.0.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go    

INFO[06:44:53] Start installing (expect) with apt-get       
INFO[06:44:53]  * [OK] Step dependency (expect) installed, available. 
INFO[06:44:53] Start installing (git) with apt-get          
INFO[06:44:53]  * [OK] Step dependency (git) installed, available. 
ERRO[06:45:00] [ENVMAN] - Failed to execute command:fork/exec TopDoc/.bitrise/toolkits/go/cache/https___github.com_bitrise-io_bitrise-steplib.git-activate-ssh-key-: no such file or directory 

activate-ssh-key (exit code: 1)

**Comment by JakeStoeffler** [comment]
Same issue, but I don't think it's this step's fault. It seems that that the bash shell is failing to initialize. You can check this by adding a bash script step at the top of your workflow and observe it still fails.  I had to change the BITRISE_SOURCE_DIR to a directory that exists and then it worked.
