### ISSUE TITLE
Add support for newer OpenSSH private keys format

### ISSUE THREAD

**Issue by goetzc** [bitrise-steplib/steps-activate-ssh-key#19]
Hi. Since OpenSSH [version 7.8](http://www.openssh.com/txt/release-7.8), private keys are created by default using the newer OpenSSH private key format (first released with OpenSSH [version 6.5](http://www.openssh.com/txt/release-6.5) on 2014) instead of the older OpenSSL's PEM format.

The new format has increased resistance to brute-force password cracking. Additionally Ed25519 keys always use the new private key format.

Currently with the latest version 4.0.5 of this step, this is the error output when using the OpenSSH private key format:

```
+------------------------------------------------------------------------------+
| (0) SSH Match certifiactes key                                               |
+------------------------------------------------------------------------------+
| id: activate-ssh-key                                                         |
| version: 4.0.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-10-09T15:22:50Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- SSHRsaPrivateKey: *****
- SSHKeySavePath: /Users/vagrant/.ssh/match_certificates_repo.key
- IsRemoveOtherIdentities: true
- Verbose: false
$ ssh-add "-l"
ssh_agent_check_result: 0
running / accessible ssh-agent detected
$ ssh-add "-D"
All identities removed.
$ ssh-agent "-k"
SSH_AGENT_PID not set, cannot kill agent
Exit code: exit status 1
$ bash "-c" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/spawn510245218/tmp_spawn.sh"
spawn ssh-add /Users/vagrant/.ssh/match_certificates_repo.key
Error loading key "/Users/vagrant/.ssh/match_certificates_repo.key": invalid format
send: spawn id exp5 not open
    while executing
"send "nopass\n""
Exit code: 1
Error, Failed to add the SSH key to ssh-agent with an empty passphrase
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | SSH Match certifiactes key (exit code: 1)                     | 3.08 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-activate-ssh-key/issues   |
| Source: https://github.com/bitrise-io/steps-activate-ssh-key                 |
+---+---------------------------------------------------------------+----------+
```

On the VM running macOS 10.15 (osx-xcode-11.7.x stack) the OpenSSH version is:
```
vagrant@prd-veg-std-p-xcode-11-7-201009151107-nwUFbTbkjfzcYLQgq9XYGi ~ % ssh -V
OpenSSH_8.1p1, LibreSSL 2.7.3
```

As a temporal workaround PEM formatted keys need to be used.

**Comment by bitce** [comment]
Thanks for this request @goetzc! We're forwarding it to the team and tooking at look at this for sure!

**Comment by compwron** [comment]
My team would also like this feature

**Comment by goetzc** [comment]
Still relevant.

**Comment by adborbas** [comment]
Hi @goetzc, 

I've took a look at the issue and would like to ask you to confirm my hypothesis before continuing with the fix. It seems that the step is capable of handling the newer OpenSSH private key format but you need to provide the key with an empty new line at the end. Keys with the previous format could be provided without a new line at the end.

Could you please retry running the Step with providing a OpenSSH private key that has an empty line at the end?
```
-----BEGIN OPENSSH PRIVATE KEY-----
the_key
-----END OPENSSH PRIVATE KEY-----
[empty line here]
```

If the hypothesis is confirmed, we will update the step to handle OpenSSH private keys provided without the new line.

Thanks for your help!
Adam

**Comment by lpusok** [comment]
Hello @goetzc, @compwron,
Released a new version of the Step that adds a newline at the end of the private key to prevent the invalid format issue.
https://discuss.bitrise.io/t/activate-ssh-key-rsa-private-key-v4-0-6/16743

**Comment by goetzc** [comment]
Hi @adborbas and @lpusok. I'm not able to test this out at the moment, but will do whenever it is possible.

Thank you!
